# Generated by Django 6.0.4 on 2026-04-18 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الكلية/التخصص')),
                ('code', models.CharField(max_length=50, verbose_name='رمز الكلية')),
                ('high_school_weight', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='نسبة معدل الثانوية (%)')),
                ('exam_weight', models.DecimalField(decimal_places=2, default=70.0, max_digits=5, verbose_name='نسبة اختبار القبول (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'الكلية',
                'verbose_name_plural': 'الكليات',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(help_text='الصف الدراسي مثلا 10، 11، 12', verbose_name='الصف الدراسي')),
                ('unit', models.IntegerField(help_text='رقم الوحدة في الكتاب', verbose_name='الوحدة')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('explanation', models.TextField(blank=True, help_text='شرح الإجابة الصحيحة', null=True, verbose_name='الشرح')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions_images/', verbose_name='صورة السؤال')),
                ('times_appeared', models.IntegerField(default=0, verbose_name='مرات الظهور في امتحانات سابقة')),
            ],
            options={
                'verbose_name': 'سؤال القبول',
                'verbose_name_plural': 'أسئلة القبول',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز المادة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'المادة',
                'verbose_name_plural': 'المواد',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجامعة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز الجامعة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/', verbose_name='شعار الجامعة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'الجامعة',
                'verbose_name_plural': 'الجامعات',
            },
        ),
        migrations.CreateModel(
            name='PDFResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('resource_type', models.CharField(choices=[('past_exam', 'نموذج اختبار سابق'), ('question_bank', 'بنك أسئلة مرجعي')], max_length=20, verbose_name='نوع الملف')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='سنة الاختبار')),
                ('file', models.FileField(upload_to='pdf_resources/', verbose_name='ملف PDF')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_resources', to='my_acceptance.college', verbose_name='الكلية')),
            ],
            options={
                'verbose_name': 'المرجع الرقمي (PDF)',
                'verbose_name_plural': 'المراجع الرقمية (PDF)',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=1, verbose_name='الحرف (A/B/C/D)')),
                ('text', models.CharField(max_length=500, verbose_name='النص')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='my_acceptance.question')),
            ],
            options={
                'verbose_name': 'خيار الإجابة',
                'verbose_name_plural': 'خيارات الإجابات',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='my_acceptance.subject', verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='college',
            name='subjects',
            field=models.ManyToManyField(related_name='required_for_colleges', to='my_acceptance.subject', verbose_name='مقررات القبول'),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('unit', 'اختبار وحدة'), ('book', 'اختبار كتاب'), ('mock', 'اختبار قبول شامل')], max_length=20, verbose_name='نوع الاختبار')),
                ('total_questions', models.IntegerField(verbose_name='عدد الأسئلة الإجمالي')),
                ('correct_answers_count', models.IntegerField(default=0, verbose_name='الإجابات الصحيحة')),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='النسبة المئوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المحاولة')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_acceptance.college', verbose_name='الكلية')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'جلسة اختبار',
                'verbose_name_plural': 'جلسات الاختبار',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_acceptance.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_acceptance.option')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='my_acceptance.testsession')),
            ],
            options={
                'verbose_name': 'إجابة الطالب',
                'verbose_name_plural': 'إجابات الطلاب',
            },
        ),
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='my_acceptance.university', verbose_name='الجامعة'),
        ),
    ]
