# Generated by Django 6.0.4 on 2026-04-19 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_acceptance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف')),
                ('device_id', models.CharField(blank=True, help_text='بصمة الجهاز لمنع مشاركة الحساب', max_length=255, null=True, verbose_name='معرف الجهاز النشط')),
                ('is_premium', models.BooleanField(default=False, help_text='تفعيل الاشتراك الشامل للطالب', verbose_name='حساب مدفوع (Premium)')),
                ('free_trials_used', models.IntegerField(default=0, help_text='عدد الامتحانات المجانية التي جربها (الحد الأقصى 2)', verbose_name='المحاولات المجانية المجراة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف الطالب (الاشتراك)',
                'verbose_name_plural': 'ملفات الطلاب (الاشتراكات)',
            },
        ),
    ]
