# Generated by Django 6.0.4 on 2026-04-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_acceptance', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='category',
            field=models.CharField(choices=[('medical', 'الكليات الطبية'), ('engineering', 'الكليات الهندسية'), ('science', 'الكليات العلمية'), ('humanities', 'الكليات الإنسانية')], default='science', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='college',
            name='icon_name',
            field=models.CharField(default='school', help_text='اسم أيقونة Flutter مثل: local_hospital, computer, science', max_length=50, verbose_name='الأيقونة'),
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_resources', to='my_acceptance.subject', verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_year',
            field=models.IntegerField(blank=True, help_text='سنة الامتحان الأصلي الذي جاء منه السؤال', null=True, verbose_name='سنة الامتحان'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_questions', to='my_acceptance.university', verbose_name='الجامعة المصدر'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='test_type',
            field=models.CharField(choices=[('unit', 'اختبار وحدة'), ('book', 'اختبار كتاب'), ('mock', 'اختبار قبول شامل'), ('year_sim', 'محاكاة سنة'), ('most_repeated', 'الأكثر تكراراً'), ('bank', 'بنك أسئلة مخصص'), ('subject_all', 'مادة شاملة')], max_length=20, verbose_name='نوع الاختبار'),
        ),
    ]
