# Generated by Django 6.0.4 on 2026-04-20 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_acceptance', '0003_college_category_college_icon_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='free_trials_used',
        ),
        migrations.AddField(
            model_name='testsession',
            name='exam_mode',
            field=models.CharField(choices=[('instant', 'الوضع التدريبي (فوري)'), ('review', 'وضع الامتحان الحقيقي')], default='instant', max_length=10, verbose_name='وضع الاختبار'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='free_challenge_trials',
            field=models.IntegerField(default=0, help_text='عدد التحديات المجانية المستخدمة (الحد: 2)', verbose_name='محاولات التحديات المجانية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='free_past_exam_trials',
            field=models.IntegerField(default=0, help_text='عدد اختبارات القبول التفاعلية المجانية المستخدمة (الحد: 2)', verbose_name='محاولات اختبارات القبول المجانية'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='test_type',
            field=models.CharField(choices=[('unit', 'اختبار وحدة'), ('book', 'اختبار كتاب'), ('mock', 'اختبار قبول شامل'), ('year_sim', 'محاكاة سنة'), ('most_repeated', 'الأكثر تكراراً'), ('bank', 'بنك أسئلة مخصص'), ('subject_all', 'مادة شاملة'), ('favorites', 'اختبار من المفضلة')], max_length=20, verbose_name='نوع الاختبار'),
        ),
        migrations.CreateModel(
            name='FavoriteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='my_acceptance.question', verbose_name='السؤال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_questions', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سؤال مفضل',
                'verbose_name_plural': 'الأسئلة المفضلة',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
