# Generated by Django 6.0.4 on 2026-04-20 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_acceptance', '0004_remove_userprofile_free_trials_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='يُخزَّن مُشفّراً ولا يمكن معرفة الكود الأصلي', max_length=64, unique=True, verbose_name='بصمة الكود (SHA-256)')),
                ('code_display', models.CharField(blank=True, help_text='يُعرض فقط عند الإنشاء ثم يُمسح تلقائياً للأمان', max_length=16, verbose_name='الكود (يظهر مرة واحدة عند الإنشاء)')),
                ('is_used', models.BooleanField(default=False, verbose_name='مُستخدَم')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('duration_days', models.IntegerField(default=365, help_text='عدد أيام الاشتراك التي يمنحها هذا الكود', verbose_name='مدة الاشتراك (أيام)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by_admin', models.CharField(blank=True, max_length=100, verbose_name='أنشأه المسؤول')),
                ('note', models.CharField(blank=True, help_text='مثال: اسم الطالب أو رقم الحوالة', max_length=255, verbose_name='ملاحظة')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to=settings.AUTH_USER_MODEL, verbose_name='استُخدم بواسطة')),
            ],
            options={
                'verbose_name': 'كود تفعيل',
                'verbose_name_plural': 'أكواد التفعيل',
                'ordering': ['-created_at'],
            },
        ),
    ]
