# Generated by Django 5.2.8 on 2026-04-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_acceptance', '0006_examdatajsonupload_alter_activationcode_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_questions', to='my_acceptance.college', verbose_name='الكلية المصدر'),
        ),
    ]
