# Generated by Django 5.2.8 on 2026-04-21 22:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_acceptance', '0007_question_source_college'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المجموعة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='my_acceptance.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'مجموعة بطاقات',
                'verbose_name_plural': 'مجموعات البطاقات',
                'unique_together': {('name', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(verbose_name='الوجه الأمامي (السؤال)')),
                ('back', models.TextField(verbose_name='الوجه الخلفي (الإجابة)')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='my_acceptance.deck', verbose_name='المجموعة')),
            ],
            options={
                'verbose_name': 'بطاقة تعليمية',
                'verbose_name_plural': 'البطاقات التعليمية',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardDocxUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='flashcard_uploads/', verbose_name='ملف Word (.docx)')),
                ('deck_name', models.CharField(max_length=255, verbose_name='اسم المجموعة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('log', models.TextField(blank=True, verbose_name='سجل المعالجة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_acceptance.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'رفع بطاقات من ملف Word',
                'verbose_name_plural': 'رفع بطاقات من ملفات Word',
            },
        ),
        migrations.CreateModel(
            name='UserFlashcardProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField(default=0, verbose_name='عدد التكرارات الناجحة')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='معامل السهولة')),
                ('interval', models.IntegerField(default=0, verbose_name='الفاصل الزمني (أيام)')),
                ('next_review_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المراجعة القادمة')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='آخر مراجعة')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='my_acceptance.flashcard', verbose_name='البطاقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقدم مراجعة بطاقة',
                'verbose_name_plural': 'تقدم مراجعة البطاقات',
                'unique_together': {('user', 'flashcard')},
            },
        ),
    ]
