# Generated by Django 5.2.8 on 2026-04-26 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_acceptance', '0009_alter_activationcode_id_alter_college_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='college',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examdatajsonupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favoritequestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flashcarddocxupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='option',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pdfresource',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userflashcardprogress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CollegeStudyGuideUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='study_guide_uploads/', verbose_name='ملف Word (.docx)')),
                ('guide_title', models.CharField(max_length=255, verbose_name='عنوان الدليل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('log', models.TextField(blank=True, verbose_name='سجل المعالجة')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_acceptance.college', verbose_name='الكلية')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_acceptance.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'رفع دليل مراجعة من ملف Word',
                'verbose_name_plural': 'رفع أدلة المراجعة من ملفات Word',
            },
        ),
        migrations.CreateModel(
            name='CollegeStudyGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: دليل مراجعة الكيمياء — طب بشري', max_length=255, verbose_name='عنوان الدليل')),
                ('content', models.TextField(help_text='المحتوى المُستخرج من ملف الوورد', verbose_name='المحتوى')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_guides', to='my_acceptance.college', verbose_name='الكلية')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_guides', to='my_acceptance.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'دليل مراجعة',
                'verbose_name_plural': 'أدلة المراجعة',
                'unique_together': {('college', 'subject')},
            },
        ),
    ]
