# Generated by Django 5.2.8 on 2026-04-26 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_acceptance', '0010_alter_activationcode_id_alter_college_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_college',
            field=models.ForeignKey(blank=True, help_text='كلية أحلام الطالب للتوصيات المخصصة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeting_students', to='my_acceptance.college', verbose_name='الكلية المستهدفة'),
        ),
    ]
