# Generated by Django 5.2.8 on 2026-04-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_acceptance', '0011_userprofile_target_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإشعار')),
                ('body', models.TextField(verbose_name='محتوى الإشعار')),
                ('icon_name', models.CharField(blank=True, help_text='مثال: science, computer, notification', max_length=50, verbose_name='اسم الأيقونة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط (يظهر للمستخدمين)')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات والإعلانات',
                'ordering': ['-created_at'],
            },
        ),
    ]
